FROM opensuse:13.2
RUN zypper --non-interactive refresh && zypper --non-interactive install \
            autoconf \
            automake \
            binutils-devel \
            bison \
            createrepo \
            expect \
            flex \
            gcc \
            gcc-c++ \
            gcc-fortran \
            gperf \
            libtool \
            libxml2-devel \
            make \
            pkg-config \
            python \
            rpm-build \
            sqlite3 \
            sqlite3-devel \
            texinfo \
        && zypper clean
